### ISSUE TITLE
Enable tslint

### ISSUE THREAD

**Issue by belohlavek** [Sqarea/sqarea#14]

**Comment by NicoSantangelo** [comment]
How do you feel about using `dcl-tslint-config-standard` ?

**Comment by belohlavek** [comment]
will refresh my memory, we need:

No unused vars (nor imports)
Consistent indentation
No var, only let/const
No implicit any
No circular dependencies (I don't remember if this one worked properly, otherwise we''ll keep madge)

and whatever else you like :)
